### PR TITLE
Enhancement/update dependencies

### PR DESCRIPTION
**Pull request by ooooooo-q**
update selenium webdriver and require Node.js > 6.9. (see https://www.npmjs.com/package/selenium-webdriver#node-support-policy )

I ran the test but inevitably the difference came out and I never succeeded.
I could not find a way to control the browser size of Firefox.

### CODE REVIEW

**Comment by azu** [comment]
> I ran the test but inevitably the difference came out and I never succeeded.

Sad 😢 
It may be related with https://github.com/SeleniumHQ/selenium/issues/2559.

**Comment by azu** [comment]
OK. It will be merged.
It contains a breaking change. We should it as major release.

**Comment by azu** [comment]
@ooooooo-q Thanks for PR.

I will add you to collaborators(GitHub/npm) if you like.
How about it?

**Comment by ooooooo-q** [comment]
@azu 

> I will add you to collaborators(GitHub/npm) if you like.

I really appreciate that. 

(My npm account is in preparation.)

**Comment by azu** [comment]
@ooooooo-q Thanks!
I've added you into collaborator 🎉

**Pull request merged**
